// Code generated by Prismic. DO NOT EDIT.

import ArticleList from "./ArticleList";
import CallToAction from "./CallToAction";
import Faq from "./Faq";
import FeaturedWebsitesList from "./FeaturedWebsitesList";
import Features from "./Features";
import Form from "./Form";
import Hero from "./Hero";
import JobList from "./JobList";
import LogoCloud from "./LogoCloud";
import Pricing from "./Pricing";
import Team from "./Team";
import Testimonials from "./Testimonials";

export const components = {
	article_list: ArticleList,
	call_to_action: CallToAction,
	faq: Faq,
	featured_websites_list: FeaturedWebsitesList,
	features: Features,
	form: Form,
	hero: Hero,
	job_list: JobList,
	logo_cloud: LogoCloud,
	pricing: Pricing,
	team: Team,
	testimonials: Testimonials
};